let trimSemicolons = /;+/g;
let trimEndSemicolon = /;$/;
let trimSpaceAroundColon = /\s*:\s*/g;
let hasCmdReg = /\x07\d+\x07/;
let spaceReg = /[ \n\f\r]+/;
let cspace = /\s+/g;
module.exports = {
    magixSpliter: '\x1e',
    artCommandReg: /\{\{(?!\{)[\s\S]*?\}\}(?!\})/g,//art模板
    microTmplCommand: /<%[\s\S]*?%>/g,
    revisableReg: /@:\{[a-zA-Z\.0-9\-\~#_&]+\}/,
    revisableGReg: /@:\{[a-zA-Z\.0-9\-\~#_&]+\}/g,
    selfCssRefReg: /@:\$\(\.?([\w\-:]+)\)/g,
    galleryFileNames: ['_config', 'config', 'cfg', '_cfg'],
    galleryFileSuffixes: ['mjs', 'js'],
    galleryAttrAppendFlag: '_',
    atViewPrefix: '@:',
    galleryProcessed: Symbol('gallery.processed'),
    galleryDynamic: Symbol('gallery.dynamic.config'),
    cssRegexpKey: Symbol('css.regexp.key'),
    tmplStoreIndexKey: Symbol('tmpl.store.index.key'),
    htmlminifier: { //html压缩器选项 https://www.npmjs.com/package/html-minifier
        removeComments: true, //注释
        collapseWhitespace: true, //空白
        quoteCharacter: '"', //属性引号
        minifyCSS(x) {
            return x.replace(trimSemicolons, ';')
                .replace(trimEndSemicolon, '')
                .replace(trimSpaceAroundColon, ':');
        },//压缩css,如标签属性中的style
        sortClassName(names) {
            if (!hasCmdReg.test(names)) {
                let xNames = names.split(spaceReg);
                names = xNames.sort().join(' ');
            } else {
                names = names.replace(cspace, ' ');
            }
            //console.log(names);
            return names;
        },
        removeEmptyAttributes: true, //移除空的属性
        collapseInlineTagWhitespace: true, //移除标签间的空白
        caseSensitive: true, //保持大小写
        keepClosingSlash: true,//保持关闭斜杠
        includeAutoGeneratedTags: false,//自动插入tag
        removeRedundantAttributes: true //移除默认的属性，如input当type="text"时 type可被移除
    },
    tmplGlobalVars: {
        window: 1,
        JSON: 1,
        document: 1,
        console: 1,
        Math: 1,
        Number: 1,
        isNaN: 1,
        typeof: 1,
        isFinite: 1,
        parseInt: 1,
        parseFloat: 1,
        Infinity: 1,
        NaN: 1,
        encodeURIComponent: 1,
        decodeURIComponent: 1,
        escape: 1,
        unescape: 1,
        encodeURI: 1,
        decodeURI: 1,
        eval: 1,
        undefined: 1,
        history: 1,
        localStorage: 1,
        sessionStorage: 1,
        navigator: 1,
        Array: 1,
        Date: 1,
        String: 1,
        Function: 1,
        Boolean: 1,
        Object: 1,
        Intl: 1,
        screen: 1,
        atob: 1,
        btoa: 1,
        performance: 1
    }, //模板中全局变量
    htmlAttrParamFlag: '*',
    htmlAttrParamPrefix: '_p_:',
    quickDirectTagName: 'qk:direct',
    quickGroupTagName: 'qk:group',
    quickDirectCodeAttr: 'qk:code',
    quickSpreadAttr: 'qk:spread',
    quickAutoAttr: 'qk:auto',
    quickOpenAttr: 'qk:open',
    quickCloseAttr: 'qk:close',
    quickForAttr: 'qk:for',
    quickForInAttr: 'qk:forin',
    quickEachAttr: 'qk:each',
    quickIfAttr: 'qk:if',
    quickElseIfAttr: 'qk:elif',
    quickElseAttr: 'qk:else',
    quickSourceArt: 'qk:srcart',
    quickDeclareAttr: 'qk:declare',
    quickGroupFnPrefix: '$groups_',
    quickLoopReg: /\b(qk:each|qk:forin)\s*=\s*(['"])([^'"]+)\2/g,
    quickConditionReg: /\b(qk:if|qk:elif|qk:for)\s*=\s*(['"])([^'"]+)\2/g,
    //tmplTempStaticKey: '_t_:static',
    tmplTempRealStaticKey: '_t_:r-static',
    tmplTempInlineStaticKey: '_t_:r-inline-static',
    tmplGroupTag: 'template',
    tmplGroupKeyAttr: '_t_:key',
    tmplGroupUseAttr: '_t_:use',
    tmplCondPrefix: '_t_:cond_',
    tmplGroupRootAttr: '_t_:root',
    tmplMxViewParamKey: '$',
    tmplStaticKey: '_',
    tmplVarTempKey: '$_temp',
    tmplMxEventReg: /\b(?:\x1c\d+\x1c)?(?:mx-|mx5-)(?!view\b|vframe\b|owner\b|html\b|static\b|is\b|as\b|type\b|name\b|to\b|from\b|ctrl\b)([a-zA-Z]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g,
    styleImportReg: /^(ref|compiled)?@?([\w\.\-\/\\]+?(?:\.css|\.less|\.mx|\.mmx|\.style))$/,
    styleDependReg: /(?:\.css|\.less|\.mx|\.mmx|\.style)$/i,
    styleInJSFileReg: /(\(\s*)?(['"]?)\(?(ref|compiled)?\x12@:([\w\.\-\/\\]+?)(\.css|\.less|\.mx|\.mmx|\.style)(?::\.?([\w\-]+))?\)?\2(\s*\))?(;?)/g,
    styleInHTMLReg: /@:([~\w\.\-\/\\]+?)(\.css|\.less|\.mx|\.mmx|\.style):\.?([\w\-]+)/g,
    cssIdGlobalPrefix: '__global__',
    cssRefReg: /\[\s*ref\s*=\s*(['"])\s*@:([\w\.\-\/\\]+?)(\.css|\.less|\.scss|\.mx|\.mmx|\.style):([\w\-]+)\1\]/g,
    cssVarRefReg: /(['"])\s*ref\s*=\s*@:([\w\.\-\/\\]+?)(\.css|\.less|\.scss|\.mx|\.mmx|\.style):([\w\-]+)\1/
};